" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

"" 关闭compatible
set nocompatible
"" 开启语法高亮
syntax on
""设置编码格式
set encoding=utf-8
"" 设置文字编码自动识别
set fencs=gbk,utf-8,ucs-bom,gb18030,gb2312,cp936
"" 使用鼠标
set mouse=a
"" 设置高亮搜索
set hlsearch
"" 输入字符串就显示匹配点
set incsearch
"" 输入的命令显示出来，看的清楚些。
set showcmd

set background=dark

set history=50 "历史记录50条
filetype plugin indent on "打开文件类型检测
""set completeopt=longest,menu "关闭智能补全时的预览窗口
"颜色方案
colorscheme Dev_Delight ""颜色方案

"界面设置.
set ruler "显示当前位置
set number "显示行号
"set nonumber "不显示行号

"格式设置.
set autoindent "自动缩进
set smartindent "智能缩进
set cindent "C缩进
set tabstop=2 "硬TAB
set softtabstop=2 "软TAB
set shiftwidth=2 "缩进空格数
set expandtab "空格替换TAB
set smarttab "智能TAB

set tags=tags; "ctags
set autochdir "ctags

"set hightlight
highlight Pmenu ctermbg=black
highlight PmenuSel ctermbg=darkblue
"hi Pmenu guibg=brown gui=bold


""""""""""""""""""""""""""""""""""""""""""""""
""
""====> Plugin
""
"""""""""""""""""""""""""""""""""""""""""""""
""
""代码折叠
""
""""""""""""""""""""""""""""""""""""""
set foldmethod=syntax
set foldlevel=100 " 启动 vim 时不要自动折叠代码

""""""""""""""""
""""""""" VIM 自动缩进
if has("autocmd")
filetype indent on
endif
"""""""""""""""

"""""""""""""""""""""""""""""""""""""
""
""在 Vim 中实现括号自动补全:
""
""""""""""""""""""""""""""""""""""""
:inoremap ( ()<ESC>i
:inoremap ) <c-r>=ClosePair(')')<CR>
:inoremap { {}<ESC>i
:inoremap } <c-r>=ClosePair('}')<CR>
:inoremap [ []<ESC>i
:inoremap ] <c-r>=ClosePair(']')<CR>
":inoremap < <><ESC>i
":inoremap > <c-r>=ClosePair('>')<CR>

function ClosePair(char)
if getline('.')[col('.') - 1] == a:char
return "\<Right>"
else
return a:char
endif
endf
""""""""

"""""""""""""""""""""""""""""""""""""""""
" => Plugin configuration
"""""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""
"NERDTreeToggle
""""""""""""""""""""""""""""""
"map<F8>:NERDTreeToggle<CR>

""""""""""""""""""""""""""""""""
" => taglist
""""""""""""""""""""""""""""""""
" taglist

"nnoremap<silent><F3>:TlistToggle<CR><CR>
set tags="~/tags"

let Tlist_Auto_Highlight_Tag = 1
"let Tlist_Auto_Open = 1
let Tlist_Auto_Update = 1
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow = 1
let Tlist_WinWidth = 20
let Tlist_Enable_Fold_Column = 0
"let Tlist_Close_On_Select = 0
"let Tlist_Compact_Format = 0
"let Tlist_Display_Prototype = 0
"let Tlist_Display_Tag_Scope = 1
"let Tlist_Enable_Fold_Column = 0
"let Tlist_File_Fold_Auto_Close = 0
"let Tlist_GainFocus_On_ToggleOpen = 1
"let Tlist_Hightlight_Tag_On_BufEnter = 1
"let Tlist_Inc_Winwidth = 0

""""""""""""""""""""""""""""""""""""""""""

""""""""""""""""""""""""""""""""""""
""
""Comments
""document-------->
""
""ctrl-c : comment a single line
""ctrl-x : un-comment a single line
""shift-v: select multiple lines, then ctrl-c to comment the selected multiple
""""line
""shift-v: select multiple lines, then ctrl-x to un-comment the selected
""""multiple line
""
""end----------->
"""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""""""""
""
""FuzzyFinder
""
""""""""""""""""""""""""""""""""""""
"let mapleader = "\\"
"map <leader>f :FufFile<CR>
"map <leader>F :FufTaggedFile<CR>
"map <leader>g :FufTag<CR>
"map <leader>b :FufBuffer<CR>
nnoremap ff :FufFile<CR>
nnoremap fb :FufBuffer<CR>
