" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

"" 关闭compatible
set nocompatible
"" 开启语法高亮
syntax on
""设置编码格式
set encoding=utf-8
"" 设置文字编码自动识别
set fencs=gbk,utf-8,ucs-bom,gb18030,gb2312,cp936
"" 使用鼠标
set mouse=a
"" 设置高亮搜索
set hlsearch
"" 输入字符串就显示匹配点
set incsearch
"" 输入的命令显示出来，看的清楚些。
set showcmd

set background=dark

set history=50 "历史记录50条
filetype plugin indent on "打开文件类型检测
""set completeopt=longest,menu "关闭智能补全时的预览窗口
"颜色方案
""colorscheme bandit "desert颜色方案

"界面设置.
set ruler "显示当前位置
set number "显示行号
"set nonumber "不显示行号

"格式设置.
set autoindent "自动缩进
set smartindent "智能缩进
set cindent "C缩进
set tabstop=2 "硬TAB
set softtabstop=2 "软TAB
set shiftwidth=2 "缩进空格数
set expandtab "空格替换TAB
"set smarttab "智能TAB

set tags=tags; "ctags
set autochdir "ctags

" TagList"
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1

" BufExplorer"
"let g:bufExplorerDefaultHelp=0
"let g:bufExplorerShowRelativePath=1
"let g:bufExplorerSortBy='mru'
"let g:bufExplorerSplitRight=0
"let g:bufExplorerSplitVertical=1
"let g:bufExplorerSplitVertSize = 30
"autocmd BufWinEnter \[Buf\ List\] setl nonumber

"" winManager setting"
"let g:winManagerWindowLayout = "FileExplorer,BufExplorer|TagList"
"let g:winManagerWidth = 30
"let g:defaultExplorer = 0
"nmap <C-W><C-F> :FirstExplorerWindow<cr>
"nmap <C-W><C-B> :BottomExplorerWindow<cr>
"nmap <silent> <leader>wm :WMToggle<cr>
"nmap <silent> <leader>wu :wa<cr>:TlistUpdate<cr>:FirstExplorerWindow<cr>

" lookupfile setting"
"let g:LookupFile_MinPatLength = 2
"let g:LookupFile_PreserveLastPattern = 0
"let g:LookupFile_PreservePatternHistory = 1
"let g:LookupFile_AlwaysAcceptFirst = 1
"let g:LookupFile_AllowNewFiles = 0
"if filereadable("./filenametags") 
"let g:LookupFile_TagExpr = '"./filenametags"'
"endif
"nmap <silent> <leader>lk :LUTags<cr>
"nmap <silent> <leader>ll :LUBufs<cr>
"nmap <silent> <leader>lw :LUWalk<cr>

" cscope setting"
"set cscopequickfix=s-,c-,d-,i-,t-,e-
"nmap <F6>s :cs find s <C-R>=expand("<cword>")<CR><CR>
"nmap <F6>g :cs find g <C-R>=expand("<cword>")<CR><CR>
"nmap <F6>c :cs find c <C-R>=expand("<cword>")<CR><CR>
"nmap <F6>t :cs find t <C-R>=expand("<cword>")<CR><CR>
"nmap <F6>e :cs find e <C-R>=expand("<cword>")<CR><CR>
"nmap <F6>f :cs find f <C-R>=expand("<cfile>")<CR><CR>
"nmap <F6>i :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
"nmap <F6>d :cs find d <C-R>=expand("<cword>")<CR><CR>

" 代码折叠
set foldmethod=syntax
set foldlevel=100 " 启动 vim 时不要自动折叠代码

" superTab
"let g:SuperTabRetainCompletionType=2
"let g:SuperTabDefaultCompletionType="<C-X><C-O>"

" ctags_highlighting
"let b:TypesFileRecurse = 1
"let b:TypesFileDoNotGenerateTags = 1
"let b:TypesFileIncludeLocals = 1
"let b:TypesFileIncludeSynMatches =1
"let b:TypesFileLanguages = ['c']

" Fn 快捷键
" F5 - LookUpFile, F6 - cscope
"nnoremap <silent> <F7> :WMToggle<CR>
"nnoremap <silent> <F8> :A<CR>

""""""""""""""""
""""""""" VIM 自动缩进
if has("autocmd")
filetype indent on
endif
"""""""""""""""

"""""""
""""在 Vim 中实现括号自动补全：
:inoremap ( ()<ESC>i
:inoremap ) <c-r>=ClosePair(')')<CR>
:inoremap { {}<ESC>i
:inoremap } <c-r>=ClosePair('}')<CR>
:inoremap [ []<ESC>i
:inoremap ] <c-r>=ClosePair(']')<CR>
:inoremap < <><ESC>i
:inoremap > <c-r>=ClosePair('>')<CR>

function ClosePair(char)
if getline('.')[col('.') - 1] == a:char
return "\<Right>"
else
return a:char
endif
endf
""""""""

"""""""""""""""""""""""""""""""""""""""""
" => Plugin configuration
"""""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""
"NERDTreeToggle
""""""""""""""""""""""""""""""
"map<F8>:NERDTreeToggle<CR>

""""""""""""""""""""""""""""""""
" => taglist
""""""""""""""""""""""""""""""""
" taglist
"let Tlist_Auto_Highlight_Tag = 1
"let Tlist_Auto_Open = 1
"let Tlist_Auto_Update = 1
"let Tlist_Close_On_Select = 0
"let Tlist_Compact_Format = 0
"let Tlist_Display_Prototype = 0
"let Tlist_Display_Tag_Scope = 1
"let Tlist_Enable_Fold_Column = 0
"let Tlist_Exit_OnlyWindow = 0
"let Tlist_File_Fold_Auto_Close = 0
"let Tlist_GainFocus_On_ToggleOpen = 1
"let Tlist_Hightlight_Tag_On_BufEnter = 1
"let Tlist_Inc_Winwidth = 0

""""""""""""""""""""""""""""""""""""""""""
